import React from 'react'
import AppIcon from './AppIcon'

const createIcon = (name, fallback) => ({ className = '', size = 20 }) => (
  <AppIcon name={name} fallback={fallback} className={className} style={{ fontSize: `${size}px` }} />
)

export const Menu = createIcon('menu', 'menu')
export const X = createIcon('close', 'close')
export const Rocket = createIcon('rocket_launch', 'rocket')
export const Info = createIcon('info', 'info')
export const Shield = createIcon('shield', 'shield')
export const Map = createIcon('map', 'map')
export const HelpCircle = createIcon('help', 'help')
export const ArrowRight = createIcon('arrow_forward', 'next')
export const Download = createIcon('download', 'download')
export const Globe = createIcon('public', 'globe')
export const Copy = createIcon('content_copy', 'copy')
export const Check = createIcon('check', 'check')
export const Lock = createIcon('lock', 'lock')
export const ExternalLink = createIcon('open_in_new', 'external')
export const Droplets = createIcon('water_drop', 'drop')
export const ShieldCheck = createIcon('verified_user', 'verified')
export const Flame = createIcon('local_fire_department', 'flame')
export const CheckCircle2 = createIcon('check_circle', 'success')
export const Loader2 = createIcon('progress_activity', 'loading')
export const ArrowLeft = createIcon('arrow_back', 'back')
export const AlertCircle = createIcon('error', 'error')
export const Monitor = createIcon('desktop_windows', 'desktop')
export const Smartphone = createIcon('smartphone', 'mobile')
export const Calculator = createIcon('calculate', 'calculator')
export const RotateCcw = createIcon('refresh', 'reset')
export const TrendingUp = createIcon('trending_up', 'up')
export const TrendingDown = createIcon('trending_down', 'down')
export const Users = createIcon('groups', 'users')
export const Wallet = createIcon('account_balance_wallet', 'wallet')
export const Settings = createIcon('settings', 'settings')
export const Unlock = createIcon('lock_open', 'unlock')
export const Database = createIcon('database', 'database')
export const Activity = createIcon('monitoring', 'activity')
export const BarChart3 = createIcon('bar_chart', 'chart')
export const AlertTriangle = createIcon('warning', 'warning')
export const Search = createIcon('search', 'search')
export const Save = createIcon('save', 'save')
export const RefreshCw = createIcon('autorenew', 'refresh')
